---
- name: deploy dogtag CA server
  become: yes
  hosts: all

  vars_files:
    - network_info.yml

  vars_prompt:

    - name: host_name
      prompt: host name
      private: no

    - name: static_ip
      prompt: static ip
      private: no

    - name: caadmin_password
      prompt: Password for caadmin
      private: yes

    - name: kraadmin_password
      prompt: Password for kraadmin
      private: yes

    - name: dirman_password
      prompt: Directory manager password
      private: yes

  vars:
    domain_joined: n

  roles:
    - linux_common
    - dogtag_ca
