---
- name: deploy windows domain controller
  hosts: all
  vars_files:
    - network_info.yml

  vars_prompt:

    - name: host_name
      prompt: Computer hostname
      private: no

    - name: domain_admin_user
      prompt: Domain Admin user
      private: no

    - name: domain_admin_password
      prompt: Domain Admin password

    - name: static_ip
      prompt: Static ip address
      private: no

    - name: safe_mode_password
      prompt: Safe mode password
      private: yes
      confirm: yes

    - name: primay_dns
      prompt: primary dns server (Not required if this is the PDC)
      private: no

    - name: pdc
      prompt: primary domain controller(y/n)
      private: no
      default: "n"

  post_tasks:
    - name: remove old ip address
      win_command: Remote-NetIPAddress -InterfaceAlias "Ethernet" -IPAddress {{ansible_default_ipv4}}

  roles:
    - windows_server
    - domain_controller