---

- name: linux common setup
  hosts: all
  become: yes
  vars_files:
    - network_info.yml

  vars_prompt:

    - name: host_name
      prompt: host name
      private: no

    - name: static_ip
      prompt: Enter static ip
      private: no

  vars:
    domain_joined: n

  post_tasks:
    - name: restart
      shell: sleep 2 && reboot
      async: 1
      poll: 0
    when: ip_change.changed


  roles:
    - linux_common