---

- name: linux common setup
  hosts: all
  become: yes
  vars_files:
    - network_info.yml

  vars_prompt:

    - name: host_name
      prompt: host name
      private: no

    - name: static_ip
      prompt: Enter static ip
      private: no

  vars:
    domain_joined: n

  roles:
    - linux_common