---

- name: linux common setup
  hosts: all
  become: yes
  vars_files:
    - network_info.yml

  vars_prompt:

    - name: host_name
      prompt: host name
      private: no

    - name: static_ip
      prompt: Enter static ip
      private: no

    - name: domain_user
      prompt: domain user
      private: no

    - name: domain_password
      prompt: domain password
      private: yes


  post_tasks:
    - name: restart
      shell: sleep 2 && reboot
      async: 1
      poll: 0


  roles:
    - linux_common