---
- name: configure vcenter
  hosts: vcenter

  tasks:
    - name: add esx host datacenter
      vmware_datacenter:
        datacenter_name: "{{datacenter}}"
        state: present
        hostname: "{{inventory_hostname}}"
        username: "{{vcenter_admin}}"
        password: "{{vcenter_password}}"
        validate_certs: no
      delegate_to: localhost

    - name: add cluster
      vmware_cluster:
        cluster_name: "{{cluster}}"
        datacenter_name: "{{datacenter}}"
        enable_drs: yes
        enable_ha: yes
        enable_vsan: no
        state: present
        hostname: "{{inventory_hostname}}"
        username: "{{vcenter_admin}}"
        password: "{{vcenter_password}}"
        validate_certs: no
      delegate_to: localhost    