---
#Wrapper for other playbooks
- name: deploy vcenter

  vars_prompt:

    - name: "vcenter_admin"
      prompt: "vcenter account"
      private: no

    - name: "vcenter_password"
      prompt: "vcenter password"

    - name: "esxi_password"
      prompt: "Root password for esxi hosts"
      private: yes
      confirm: yes

    - name:

  vars:
    datacenter: datacenter-1
    cluster:  cluster-1
    vlan_id: 0

- include: vcenter.yml
- include: esx_host.yml