---

- name: deploy windows
  hosts: all

  vars_files:
    - network_info.yml

  vars_prompt:

    - name: host_name
      prompt: Computer hostname
      private: no

    - name: domain_user
      prompt: Domain Admin user
      private: no

    - name: domain_password
      prompt: Domain Admin password

    - name: static_ip
      prompt: Static ip address
      private: no


  post_tasks:
    - name: set new IP
      win_shell: >
        New-NetIPAddress -InterfaceAlias "Ethernet" -IPAddress {{static_ip}} -DefaultGateway {{gateway}} -PrefixLength 24;
        Remove-NetIpAddress -InterfaceAlias "Ethernet" -IPAddress {{ansible_ip_addresses[0]}}
        Remove-WSManInstance -ResourceUri  winrm/config/Listener -SelectorSet @{address="*";transport="https"};
        Restart-Computer -Force
      args:
        executable: powershell.exe
      poll: 0
      async: 1
      when: static_ip not in ansible_ip_addresses

  roles:
    - windows_server