---

- name: install packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - 389-ds-base
    - pki-base
    - pki-server
    - pki-ca

- name: add pam_limits to system-auth
  lineinfile:
    path: /etc/pam.d/system-auth
    insertafter: "# User changes will be destroyed the next time authconfig is run."
    line: session required pam_limits.so
  register: pam

- name: ensure sysctl.conf is configured
  blockinfile:
    path: /etc/sysctl.conf
    state: present
    block: >
      net.ipv4.tcp_keepalive_time = 300

      net.ipv4.ip_local_port_range = 1024 65000

      fs.file-max = 64000
  register: sysctl

- name: set sysctl 
  command: sysctl -p
  when: sysctl.changed 

- name: up file descriptor limit
  lineinfile:
    path: /etc/security/limits.conf
    line: "*        -        nofile        8192"

- name: copy cfgs to /tmp
  template:
    src: "{{item}}"
    dest: /tmp/
  with_items:
    - ca.cfg
    - ds.cfg

- name: reboot
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  when: pam.changed

- name: wait for connection
  wait_for_connection:
    delay: 10

- name: run setup-ds.pl
  command: setup-ds.pl --silent --file=/tmp/ds.cfg
  when: sysctl.changed

- name: ensure 389-ds is running
  service:
    name: dirsrv.target
    state: started
    enabled: yes

- name: run pkispawn for CA
  command: pkispawn -s CA -f /tmp/ca.cfg
  notify: ensure_pki

#- name: remove sensitive config files
#  file:
#    path: /tmp/{{item}}
#    state: absent
#  with_items:
#    - ca.cfg
#    - ds.cfg