---

- name: install packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - 389-ds-base
    - pki-server

- name: ensure sysctl.conf is configured
  blockinfile:
    path: /etc/sysctl.conf
    state: present
    block: >
      net.ipv4.tcp_keepalive_time = 300

      net.ipv4.ip_local_port_range = 1024 65000

      fs.file-max = 64000
  register: sysctl

- name: set sysctl 
  command: sysctl -p
  when: sysctl.changed 

- name: up file descriptor limit
  lineinfile:
    path: /etc/security/limits.conf
    line: "*        -        nofile        8192"

- name: copy ca.cfg to /tmp
  template:
    src: ca.cfg
    dest: /tmp/ca.cfg

- name: run setup-ds.pl
  shell: >
    setup-ds.pl --silent\
    General.FullMachineName="{{host_name}}.{{domain}}"\
    General.SuiteSPotUserID=nobody\
    General.SuiteSPotGroup=nobody\
    slapd.ServerPort=389\
    slapd.ServerIdentifier=pki-tomcat\
    slapd.Suffix=dc=internal,dc=homelab,dc=systems\
    slapd.RootDN="cn=Directory Manager"\
    slapd.RootDNPwd="{{dirman_password}}"

- name: run pkispawn for CA
  command: pkispawn -s CA -f /tmp/ca.cfg

- name: run pkispawn for KRA
  command: pkispawn -s KRA -f /tmp/ca.cfg