---

- name: firewall
  firewalld:
    service: "{{item}}"
    state:  enabled
    permanent: yes
  with_items:
    - http
    - tftp

#- name: start and enable tfpd
#  service:
#    name: tftp
#    state: started
#    enabled: yes
#    use: service

- name: install packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - httpd
    - tftp-server
    - syslinux-tftpboot
    - xinetd

- name: set tftp sebool
  seboolean:
    name: tftp_anon_write
    state: yes
    persistent: yes

- name: create pxelinux.cfg dir
  file:
    path: /var/lib/tftpboot/pxelinux.cfg/
    state: directory

- include_tasks: centos.yml

- name: copy xinetd config
  copy:
    src: tftp
    dest: /etc/xinetd.d/tftp
  notify: ensure_tftp

- name: copy pxe config template
  template:
    src: default
    dest: /var/lib/tftpboot/pxelinux.cfg/default
  notify: ensure_tftp

- name: copy apache welcome conf
  copy:
    src: welcome.conf
    dest: /etc/httpd/conf.d/welcome.conf
  notify: ensure_httpd